//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManage.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ANKEN
    {
        public long SEQ { get; set; }
        public long ANKEN_ID { get; set; }
        public string ANKEN_NAME { get; set; }
        public long DEL_FLG { get; set; }
    }
}
